version: 2
jobs:
  abas:
    docker:
      - image: python:3.8

    steps:
    - checkout
    - run:
        name: SetUp_Lev
        command: |
          chmod u+x *
          timeout 60s su | python main.py






workflows:
  version: 2
  abas:
    jobs:
    - abas
